### ISSUE TITLE
ext格式固件用dd写入tf卡后，无法获取到ip

### ISSUE THREAD

**Issue by luoei** [nekomi-cn/OrangePi-R1-Plus-LTS-Lede#2]
启动后，双网卡灯会亮，前面sys红灯闪烁，电脑上获取不到ip地址，电脑上获取的是169开头的私有地址。

**Comment by nekomi-cn** [comment]
ext 格式的固件没有测试过，测试使用的是 squashfs 格式的固件。有问题可以去 https://github.com/coolsnowwolf/lede 提，这里只负责打包

**Comment by nekomi-cn** [comment]
![image](https://user-images.githubusercontent.com/78152109/164889481-35deebe1-0979-4eef-b17b-fb34a975ba7e.png)
